database/migrations/2021_08_23_084340_create_categories_table.php, database/migrations/2021_08_23_084441_create_books_table.php, database/migrations/2021_08_23_084515_create_roles_table.php, database/migrations/2021_08_23_084516_create_users_table.php, database/migrations/2021_08_23_084729_create_reviews_table.php, database/migrations/2021_08_23_084830_create_follows_table.php, database/migrations/2021_08_23_084919_create_favorites_table.php, database/migrations/2021_08_23_085000_create_comments_table.php, database/migrations/2021_08_23_085100_create_requests_table.php, database/migrations/2021_08_23_085134_create_likes_table.php, database/migrations/2021_08_23_085211_create_images_table.php
- [#40788](https://edu-redmine.sun-asterisk.vn/issues/40788)
- add migration
- N/A.
-
=> init migration

.gitignore, app/Http/Controllers/Auth/RegisterController.php, app/Http/Requests/RegisterUserRequest.php, config/app.php, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
- [#40862](https://edu-redmine.sun-asterisk.vn/issues/40862
- Done form register
- Done user register
- N/A.
=> done user register

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/CommentController.php, app/Http/Controllers/ReviewController.php, app/Http/Requests/CreateCommentRequest.php, app/Http/Requests/CreateReviewRequest.php, app/Http/Requests/EditCommentRequest.php, app/Http/Requests/EditReviewRequest.php, app/Models/Review.php, app/helpers.php, composer.json, config/app.php, database/migrations/2021_08_23_084729_create_reviews_table.php, resources/lang/en/messages.php, resources/lang/vi/messages.php, routes/web.php
- [#40701](https://edu-redmine.sun-asterisk.vn/issues/40701)
- [#40702](https://edu-redmine.sun-asterisk.vn/issues/40702)
- [#40703](https://edu-redmine.sun-asterisk.vn/issues/40703)
- [#40708](https://edu-redmine.sun-asterisk.vn/issues/40708)
- [#40709](https://edu-redmine.sun-asterisk.vn/issues/40709)
- [#40710](https://edu-redmine.sun-asterisk.vn/issues/40710)
- User add, edit, delete comment (controller)
- User add, edit, delete review (controller)
- Fix message when register successful
- Update table structure of Review
- N/A.
- N/A.
=> Comment & Review Controller

app/Http/Controllers/UserController.php, app/helpers.php, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/layouts/app.blade.php, resources/views/profile.blade.php, routes/web.php
- [#40705](https://edu-redmine.sun-asterisk.vn/issues/40705)
- [#40707](https://edu-redmine.sun-asterisk.vn/issues/40707)
- Add template user profile
- In user profile has user's info + review history
- Auth user can see other user profile + review history
- N/A.
=> user-review-history

app/Http/Controllers/BookController.php, app/Http/Controllers/UserController.php, app/Providers/AppServiceProvider.php, config/app.php, resources/css/home.css, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/layouts/app.blade.php, resources/views/user/index.blade.php, resources/views/user/layouts/header.blade.php, resources/views/user/layouts/layout.blade.php, resources/views/user/layouts/sidebar.blade.php, routes/web.php
- [#40692](https://edu-redmine.sun-asterisk.vn/issues/40692)
- [#40694](https://edu-redmine.sun-asterisk.vn/issues/40694)
- View list books and search book by title
- N/A.
-
=> list book and search by title

app/Http/Controllers/FollowController.php, app/Http/Controllers/UserController.php, app/Models/Follow.php, app/Models/User.php, composer.json, composer.lock, public/mix-manifest.json, resources/css/home.css, resources/js/profile.js, resources/js/vendor/I18n.js, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/user/profile.blade.php, routes/web.php, webpack.mix.js
- [#40713] https://edu-redmine.sun-asterisk.vn/issues/40713
follow/unfollow an user using ajax
- N/A.
https://user-images.githubusercontent.com/86346191/132244842-997d092f-248e-44eb-aeb9-13e3688eadb7.mp4
=> follow-unfollow management

app/Http/Controllers/BookController.php, app/Http/Controllers/ReviewController.php, app/Models/Review.php, config/app.php, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/book-detail.blade.php, routes/web.php
- [#41122](https://edu-redmine.sun-asterisk.vn/issues/41122)
- Done template book detail for user
- Complete add, edit, delete review 
- Complete add. edit, delete comment
- N/A.
https://user-images.githubusercontent.com/44666485/132191736-927f5839-5424-4142-949f-7e55f05a61eb.mp4
=> Done view detail-book

app/Http/Controllers/BookController.php, resources/views/user/index.blade.php
- Fix bug of book detail page
- Link book-detail route to view
- N/A.
- N/A.
=> fix bug book-detail

app/Http/Controllers/CommentController.php, app/Http/Controllers/ReviewController.php, app/Http/Requests/CreateCommentRequest.php, app/Http/Requests/CreateReviewRequest.php, app/Http/Requests/EditCommentRequest.php, app/Http/Requests/EditReviewRequest.php, app/Policies/CommentPolicy.php, app/Policies/ReviewPolicy.php, app/Providers/AuthServiceProvider.php, resources/lang/en/messages.php, resources/lang/vi/messages.php
- update authorization for user by using policy
- N/A.
- N/A.
=> update authorization by using policy

resources/css/home.css, resources/js/home.js, resources/views/book-detail.blade.php, resources/views/layouts/app.blade.php
- Update view of book detail
- N/A.
=> Update book-detail view

app/Http/Controllers/HomeController.php, app/Models/User.php, bower.json, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/admin/layouts/layout.blade.php, resources/views/layouts/app.blade.php, resources/views/user/favorite_books.blade.php, resources/views/user/index.blade.php, resources/views/user/layouts/header.blade.php, resources/views/user/layouts/layout.blade.php, resources/views/user/layouts/sidebar.blade.php, resources/views/user/search_book.blade.php
- [#Ticket ID]
- Update layout user
- N/A.
- 
https://user-images.githubusercontent.com/78576331/133022385-9a4723b5-312a-469a-84e8-fab276747529.mp4
=> update layout user

.gitignore, tests/ModelTestCase.php, tests/Unit/Models/BookTest.php, tests/Unit/Models/CategoryTest.php, tests/Unit/Models/FollowTest.php
Test model:
- Category
- Book
- Follow
- N/A.
=> test category, book, follow model

app/Http/Controllers/LikeController.php, app/Providers/AppServiceProvider.php, app/Repositories/BaseRepository.php, app/Repositories/Book/BookRepository.php, app/Repositories/Book/BookRepositoryInterface.php, app/Repositories/Like/LikeRepository.php, app/Repositories/Like/LikeRepositoryInterface.php, app/Repositories/RepositoryInterface.php, database/factories/BookFactory.php, tests/Unit/Http/Controllers/LikeControllerTest.php
=> test LikeController

app/Http/Controllers/UserController.php, app/Providers/AppServiceProvider.php, app/Repositories/BaseRepository.php, app/Repositories/Follow/FollowRepository.php, app/Repositories/Follow/FollowRepositoryInterface.php, app/Repositories/Review/ReviewRepository.php, app/Repositories/Review/ReviewRepositoryInterface.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, database/factories/FollowFactory.php, database/factories/ReviewFactory.php, resources/js/manage_user.js, resources/views/admin/users/index.blade.php, routes/web.php, tests/Unit/Http/Controllers/UserControllerTest.php
- Change enable(), disablel() of UserController to changeUserStatus() function
- Test UserController
- N/A.
-
=> test UserController

app/Http/Controllers/CommentController.php, app/Providers/AppServiceProvider.php, app/Repositories/Comment/CommentRepository.php, app/Repositories/Comment/CommentRepositoryInterface.php, database/factories/CommentFactory.php, tests/Unit/Http/Controllers/CommentControllerTest.php
- Unit Test CommentController
- N/A.
- ![image](https://user-images.githubusercontent.com/44666485/134108731-0e8bbb51-ff2d-414e-a560-8cea51c84273.png)
=> Unit Test CommentController

composer.json, composer.lock, tests/Browser/CreateBookTest.php, tests/Browser/Pages/CreateBookPage.php, tests/Browser/Pages/Page.php, tests/Browser/console/.gitignore, tests/Browser/screenshots/.gitignore, tests/Browser/source/.gitignore, tests/DuskTestCase.php
- Test create-book view
- N/A.
=> test create-book-view

tests/Browser/Pages/UserManagementPage.php, tests/Browser/UserManagementTest.php
- Test user management view
- N/A.
=> test user management view

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/BookController.php, app/Http/Controllers/FavoriteController.php, app/Http/Controllers/FollowController.php, app/Http/Controllers/HomeController.php, app/Repositories/Book/BookRepository.php, app/Repositories/Book/BookRepositoryInterface.php, app/Repositories/Category/CategoryRepository.php, app/Repositories/Category/CategoryRepositoryInterface.php, app/Repositories/Favorite/FavoriteRepository.php, app/Repositories/Favorite/FavoriteRepositoryInterface.php, app/Repositories/Image/ImageRepository.php, app/Repositories/Image/ImageRepositoryInterface.php, resources/views/book-detail.blade.php
- [#42049](https://edu-redmine.sun-asterisk.vn/issues/42049)
- Change to use repository part 2
- N/A.
- N/A.
=> change to use repository part 2

app/Http/Kernel.php, app/Http/Middleware/MarkNotificationAsRead.php, resources/css/home.css, resources/js/realtime-follow-notify.js, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/user/layouts/header.blade.php, routes/web.php
-[#42146] https://edu-redmine.sun-asterisk.vn/issues/42146
- mark notification as read
- N/A.
https://user-images.githubusercontent.com/86346191/135782719-23bb6037-4d12-41c5-9405-bb40ef7fe81c.mp4
=> add mark notification as read

app/Http/Controllers/BookController.php, app/Models/User.php, app/Notifications/FavoriteBookNotification.php, app/Repositories/Book/BookRepository.php, app/Repositories/Favorite/FavoriteRepository.php, app/Repositories/Favorite/FavoriteRepositoryInterface.php, public/mix-manifest.json, resources/css/home.css, resources/js/notify_when_favorite_book_deleted.js, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/book-detail.blade.php, resources/views/user/layouts/header.blade.php, resources/views/user/layouts/layout.blade.php, routes/channels.php, routes/web.php, webpack.mix.js
- [#42147](https://edu-redmine.sun-asterisk.vn/issues/42147)
- Realtime notification when favorite book has been deleted
- N/A.
https://user-images.githubusercontent.com/78576331/135818829-c23ed272-1cb7-420e-80ed-a3f72a00a41b.mp4
=> realtime notification when favorite book has been deleted

app/Console/Kernel.php, app/Jobs/SendEmailFavoriteBook.php, app/Mail/MailNotifyFavoriteBook.php, app/Repositories/Book/BookRepository.php, app/Repositories/Favorite/FavoriteRepository.php, app/Repositories/Favorite/FavoriteRepositoryInterface.php, config/app.php, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/emails/favorite_book_review.blade.php
- [#42369](https://edu-redmine.sun-asterisk.vn/issues/42369)
- Schedule mail for statistic reviews of favorite books
- N/A.
- ![image](https://user-images.githubusercontent.com/78576331/136490077-e72105fb-31ec-4671-abfb-3e884b8713ed.png)
=> Schedule mail for statistic reviews of favorite books

app/Http/Controllers/BookController.php, app/Repositories/Book/BookRepository.php, app/Repositories/Book/BookRepositoryInterface.php, config/menu.php, package-lock.json, package.json, public/mix-manifest.json, resources/css/home.css, resources/js/book_statistic.js, resources/lang/en/messages.php, resources/lang/vi/messages.php, resources/views/admin/books/book_statistic.blade.php, routes/web.php, webpack.mix.js
- [#42396](https://edu-redmine.sun-asterisk.vn/issues/42396)
- Draw chart for like, review, comment statistic
- N/A.
-
=> draw chart for like, review, comment statistic

tests/Unit/Console/KernelTest.php, tests/Unit/Jobs/SendEmailFavoriteBookTest.php, tests/Unit/Notifications/FavoriteBookNotificationTest.php
- Add unit test for project 2
- N/A.
-
=> add unit test for project 2
